[theme]
primaryColor = "#4F252E"
backgroundColor = "#C1EBE9"
font = "Averia Libre:https://fonts.googleapis.com/css2?family=Averia+Libre:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
headingFont = "Jua:https://fonts.googleapis.com/css2?family=Jua&display=swap"
codeFont = "monospace"